/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --transform --keepmeshes public/apparelbooth.glb 
Files: public/apparelbooth.glb [122.9MB] > C:\Users\bosic\Documents\bscnapps\3dsite\apparelbooth-transformed.glb [2.15MB] (98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/apparelbooth-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ground.geometry} material={materials['Material.001']} position={[1.77, 0, 10.9]} rotation={[0, 1.553, 0]} scale={[24.851, 31.482, 13.965]} />
      <mesh geometry={nodes.TShirtFaceDown.geometry} material={materials.StudioOchi_Black} position={[-3.181, 6.19, 16.77]} rotation={[-0.43, 0.765, -2.589]} scale={0.561} />
      <mesh geometry={nodes.TShirtFaceUp.geometry} material={materials.StudioOchi_Mapper} position={[-3.181, 6.19, 16.77]} rotation={[2.398, 1.111, -2.207]} scale={0.561} />
      <mesh geometry={nodes.TShirtFaceUp002.geometry} material={materials.StudioOchi_Yellow} position={[-2.971, 6.867, 15.812]} rotation={[1.6, 1.265, -1.357]} scale={0.588} />
      <mesh geometry={nodes.TShirtMan.geometry} material={materials['StudioOchi.Blue']} position={[-7.595, 3.172, 14.061]} rotation={[Math.PI / 2, 0, -0.982]} scale={0.589} />
      <mesh geometry={nodes.TShirtWoman.geometry} material={materials.StudioOchi_White2} position={[-8.59, 3.084, 16.293]} rotation={[Math.PI / 2, 0, -0.982]} scale={0.579} />
      <mesh geometry={nodes.bscnframe.geometry} material={materials.BlackSteel} position={[-9.238, 18.916, -14.506]} rotation={[Math.PI / 2, 0, 0]} scale={0.09} />
      <mesh geometry={nodes.bscnframe002.geometry} material={materials.StudioOchi_Yellow} position={[0.226, 18.791, -14.259]} rotation={[Math.PI / 2, 0, 0]} scale={0.09} />
      <mesh geometry={nodes.bscnframe001.geometry} material={materials.StudioOchi_White} position={[-9.213, 11.827, -14.707]} rotation={[Math.PI / 2, 0, 0]} scale={0.09} />
      <mesh geometry={nodes.bscnframe003.geometry} material={materials.StudioOchi_White2} position={[0.252, 11.701, -14.46]} rotation={[Math.PI / 2, 0, 0]} scale={0.09} />
      <mesh geometry={nodes.bscnframe004.geometry} material={materials['Material.001']} position={[9.029, 18.665, -14.247]} rotation={[Math.PI / 2, 0, 0]} scale={0.09} />
      <mesh geometry={nodes.bscnframe005.geometry} material={materials.StudioOchi_Black} position={[9.055, 11.576, -14.448]} rotation={[Math.PI / 2, 0, 0]} scale={0.09} />
      <mesh geometry={nodes.bscnframe006.geometry} material={materials['StudioOchi.Blue']} position={[18.494, 18.54, -14]} rotation={[Math.PI / 2, 0, 0]} scale={0.09} />
      <mesh geometry={nodes.bscnframe007.geometry} material={nodes.bscnframe007.material} position={[18.52, 11.45, -14.201]} rotation={[Math.PI / 2, 0, 0]} scale={0.09} />
      <mesh geometry={nodes.Woman02_Med.geometry} material={materials.BlackSteel} position={[-8.724, 2.768, 16.324]} rotation={[Math.PI / 2, 0, -0.925]} scale={[5.652, 4.176, 5.935]} />
      <mesh geometry={nodes.MannequinMan.geometry} material={materials.BlackSteel} position={[-7.573, 2.574, 14.029]} rotation={[Math.PI / 2, 0, -0.995]} scale={[4.445, 4.04, 5.66]} />
      <mesh geometry={nodes.Hanger.geometry} material={materials.BlackSteel} position={[-8.548, -5.693, 19.642]} rotation={[-Math.PI, 1.274, -Math.PI]} scale={[0.744, 1.11, 0.01]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.BlackSteel} position={[-8.396, -0.2, 16.772]} rotation={[0, Math.PI / 3, 0]} scale={[7.939, 7.022, 4.97]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.BlackSteel} position={[-7.573, 0.07, 13.91]} rotation={[0, 1.431, 0]} scale={[7.939, 7.022, 4.97]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.BlackSteel} position={[-9.611, -0.41, 19.57]} rotation={[Math.PI, -0.036, Math.PI]} scale={[7.915, 6.951, 9.997]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials.BlackSteel} position={[-1.137, 0.08, 14.825]} rotation={[0, Math.PI / 2, 0]} scale={[6.422, 8.628, 6.69]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials.BlackSteel} position={[-1.137, 0.08, -0.815]} rotation={[0, Math.PI / 2, 0]} scale={[6.422, 8.628, 6.69]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[-3.077, 5.28, 16.645]} rotation={[0, Math.PI / 2, 0]} scale={[6.72, 1, 7.11]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-3.077, 5.28, 1.065]} rotation={[0, Math.PI / 2, 0]} scale={[6.72, 1, 7.11]} />
      <mesh geometry={nodes.plaster001.geometry} material={materials.StudioOchi_White2} position={[-2.779, 6.985, 3.954]} rotation={[Math.PI / 2, 0, 0.916]} scale={0.105} />
      <mesh geometry={nodes['02_pastel_planter_stl'].geometry} material={materials.StudioOchi_Mapper} position={[-1.361, 6.444, 3.351]} scale={0.117} />
      <mesh geometry={nodes.bscn_rombo_vase.geometry} material={materials.StudioOchi_Black} position={[-0.913, 6.775, -1.887]} scale={0.137} />
      <group position={[-3.103, 7.209, 0.551]} rotation={[Math.PI / 2, 0, 0]} scale={0.156}>
        <mesh geometry={nodes.cutlery_1.geometry} material={materials['material0.001']} />
        <mesh geometry={nodes.cutlery_2.geometry} material={materials['material0.001']} />
      </group>
      <mesh geometry={nodes.TShirtHanger.geometry} material={materials.StudioOchi_White} position={[-8.434, 3.187, 19.654]} rotation={[1.571, 0, -1.856]} scale={0.561} />
    </group>
  )
}

useGLTF.preload('/apparelbooth-transformed.glb')
