/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --transform --keepmeshes public/EV2.glb 
Files: public/EV2.glb [144.55KB] > C:\Users\bosic\Documents\bscnapps\3dsite\EV2-transformed.glb [9.4KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/EV2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.EV_Type_1_Connector_Cap_2.geometry} material={nodes.EV_Type_1_Connector_Cap_2.material} />
    </group>
  )
}

useGLTF.preload('/EV2-transformed.glb')
